# Generated by Django 4.2.7 on 2023-11-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'playlist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlaylistSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inserted_timestamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'playlist_song',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_timsetamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'recommendation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('content', models.CharField(blank=True, max_length=1000, null=True)),
                ('song_rating', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'review',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReviewRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_rating', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'review_rating',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('artist', models.CharField(blank=True, max_length=100, null=True)),
                ('album_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('song_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('popularity', models.IntegerField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('explicit', models.IntegerField(blank=True, null=True)),
                ('danceability', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('energy', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('key', models.IntegerField(blank=True, null=True)),
                ('loudness', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('mode', models.IntegerField(blank=True, null=True)),
                ('speechiness', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('acousticness', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('instrumentalness', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('liveness', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('valence', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('tempo', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('time_signature', models.IntegerField(blank=True, null=True)),
                ('song_genre', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'song',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SongHistory',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('listened_timestamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'song_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('password_salt', models.CharField(blank=True, max_length=32, null=True)),
                ('password_hash', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
